imports:
    - { resource: parameters.yml }

framework:
  secret:          "%secret%"

parameters:
  chameleon_system_shop.article_list.view_to_list_view_mapping:
    rightNoticeList:           "/common/lists/listStandardShopArticle.html.twig"
    full:                      "/common/lists/listExtendedShopArticle.html.twig"
    standardEmptyOnNoArticles: "/common/lists/listScrollShopArticle.html.twig"
    standard:                  "/common/lists/listScrollShopArticle.html.twig"

chameleon_system_cms_text_field:
  allow_script_tags: false

chameleon_system_java_script_minification:
  js_minifier_to_use: "jshrink"

monolog:
  # NOTE this channel list is not / must not be a complete list.
  # It is only necessary here in advance for backwards-compatibility (ie users of "IPkgCmsCoreLog" and any Tdb or TCMS object).
  channels:
    - "core_standard"
    - "core_security"
    - "core_dbal"
    - "core_cms_updates"
    - "core_cronjobs"
    - "core_api"

  handlers:
    database:
      type: service
      id: cmsPkgCore.logHandler.database
      channels:
      - "core_security"
      - "core_cms_updates"
      - "core_cronjobs"
      - "core_api"

    database_for_fingers_crossed:
      type: service
      id: cmsPkgCore.logHandler.database

    standard:
      type: fingers_crossed
      handler: database_for_fingers_crossed
      channels:
      - "core_standard"

    dbal:
      type: stream
      path: "%kernel.logs_dir%/dbal.log"
      channels:
        - "core_dbal"
      level: warning
